enum TestEnum : u8 {
    FOO,
    BAR,
    BAZ
};

struct Header {
    channel: string;
    topic: string;
    sequence_number: u64;
};

struct TestStruct {
    header: Header;
    a: list[i8];
    b: boolean;
    c: string;
    d: tuple[string, list[u8]];
    e: union[
        TestEnum, map[i8, i8]
    ];
    f: blob;
}

